### ISSUE TITLE
Any examples ?

### ISSUE THREAD

**Issue by Hydro8** [atbyrd/Withings.NET#3]
Hi

Thank a lot to work on this ! 

I know it isn't finish yet but do you have some examples to start working on it ?

Thank again.

**Comment by antarr** [comment]
You can have a look at the [Nancy example](https://github.com/atbyrd/Withings.NET/blob/master/NancyExample/Modules/IndexModule.cs) for how authorization works.

**Comment by Hydro8** [comment]
I tried it but I have a problem with Authenticator.
It didn't find the type or namespace for Authenticator, I tried to install Nancy and Quantfabric but it didn't change.
Any idea ?

**Comment by antarr** [comment]
What version of Quantfabric are you using? It should probably be 1.3.6. There a quite a few changes between it and the latest version.

**Comment by antarr** [comment]
@Hydro8  You should be using Quantfabric 1.3.7 in your client application.

**Comment by Hydro8** [comment]
I use Quantfabric.Material 1.3.8 :(

**Comment by antarr** [comment]
@Hydro8  I had to rename the project. You can find it @ https://www.nuget.org/packages/Withing.NET/1.1.1

**Comment by antarr** [comment]
@Hydro8  You should be fine with 1.3.8. I just used it with same version in another project. Try getting the latest release Withing.NET

**Comment by Hydro8** [comment]
It's ok for this problem, now I have "The name Get does not exist in the current context".
I copy every using from nancy example but it isn't working :(

**Comment by antarr** [comment]
@Hydro8  Where is it being thrown. Post the full error.

**Comment by Hydro8** [comment]
Ok I use it with my home automation system so I must put everything into MessageCallback to launch it with a button on my interface

PackageHost.WriteInfo allow to display message on my HA log so I use it to see if function work well.

Here my code so far
```
using Constellation;
using Constellation.Package;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Nancy;
using Nancy.Responses;
using Newtonsoft.Json;
using Withings.NET.Client;
using System.Configuration;
using Foundations.HttpClient.Enums;
using Material.Infrastructure.Credentials;
using Material.Infrastructure.Responses;

namespace Withings2
{
    public class Program : PackageBase
    {
        static void Main(string[] args)
        {
            PackageHost.Start<Program>(args);
        }

        public override void OnStart()
        {
            PackageHost.WriteInfo("Package starting - IsRunning: {0} - IsConnected: {1}", PackageHost.IsRunning, PackageHost.IsConnected);
        }

        [MessageCallback]
        public void Auth()
        {
            var _credentials = new OAuth1Credentials();
            _credentials.SetCallbackUrl("google.com");
            _credentials.SetConsumerProperties("4234125cc9e9e44bdc8181ce41e6b6e5c6fd8e17202b05ceb4cdec4185d", "fe7405871f7777c19f1893bc5532f53480debb1f7ec3f2149f32f5c9d4d8c76");
            _credentials.SetParameterHandling(HttpParameterType.Querystring);

            var authenticator = new Authenticator(_credentials);

            var test = new RedirectResponse("api/oauth/authorize", RedirectResponse.RedirectType.Permanent);

            PackageHost.WriteInfo("{0}", test.StatusCode);

            Get["/"] = nothing => new RedirectResponse("api/oauth/authorize", RedirectResponse.RedirectType.Permanent);

            Get["api/oauth/authorize", true] =
                async (nothing, ct) =>
                    new RedirectResponse(await authenticator.UserRequstUrl("nancy_user").ConfigureAwait(true));

            Get["api/oauth/callback", true] = async (nothing, ct) =>
            {
                var credentials =
                    await authenticator.ExchangeRequestTokenForAccessToken(Request.Url, "nancy_user")
                        .ConfigureAwait(true);

                ConfigurationManager.AppSettings["OAuthToken"] = credentials.OAuthToken;
                ConfigurationManager.AppSettings["OAuthSecret"] = credentials.OAuthSecret;
                ConfigurationManager.AppSettings["UserId"] = credentials.ExternalUserId;
                return new JsonResponse<OAuth1Credentials>(credentials, new DefaultJsonSerializer());
            };

        }
        
    }
}
`

**Comment by antarr** [comment]
@Hydro8  Where does the messagecallback attribute come from? It looks like it should be above `Get["api/oauth/callback", true]`

**Comment by Hydro8** [comment]
It come from my HA library Constellation. 

Is it possible to have the URL into var that I can display with WriteInfo ?

**Comment by antarr** [comment]
@Hydro8 Which url are you referring to?

**Comment by Hydro8** [comment]
The withings URL the user must visit to authorize the application

**Comment by antarr** [comment]
@Hydro8  You can get that from `authenticator.UserRequstUrl("nancy_user")`. I"ll make a update shortly where the username is not required.

**Comment by Hydro8** [comment]
The username is from Nancy ?

**Comment by antarr** [comment]
Its part of quantfabric, you can put anything there as long as its unique

**Comment by antarr** [comment]
I just releases version 3.0 https://www.nuget.org/packages/Withings.NET @Hydro8 . There are major changes in the Nancy project.

**Comment by Hydro8** [comment]
I just try with this code

`        public void Auth()
        {
            var _credentials = new OAuth1Credentials();
            _credentials.SetCallbackUrl("google.com");
            _credentials.SetConsumerProperties("xxx", "xxx");
            _credentials.SetParameterHandling(HttpParameterType.Querystring);

            var authenticator = new Authenticator(_credentials);

            PackageHost.WriteInfo("{0}", authenticator.UserRequestUrl("test"));

        }`

But I have a bug on nancy username. It said that I must provide a RequestToken not a string.

**Comment by antarr** [comment]
@hydro8 be it not longer accepts a username. You have to first get the request token and pass it. It's in the updated examples project.

**Comment by Hydro8** [comment]
Ok I try to start with the example but I'm stuck with "The name Get does not exist in the current context" even if I put get before my callback.

Do you know how to use it as function ?

Sorry I'm a beginner in C#

**Comment by antarr** [comment]
What line number is this on @Hydro8 . Did you import Nancy?

```
using Nancy;
using Nancy.Helpers;
using Nancy.Responses;
```

**Comment by Hydro8** [comment]
Yes because it won't work before. I remove it but it doesn't change a thing.

**Comment by antarr** [comment]
@Hydro8 Is the solution you working in based of Nancy or something else?

**Comment by Hydro8** [comment]
I don't know I just installed your library and quantum fabric.
After I tried to copy your code but it's not working.

**Comment by antarr** [comment]
@Hydro8 Do you have a public repo of your code?

**Comment by Hydro8** [comment]
No but I can try to do it

**Comment by Hydro8** [comment]
Hi
Sorry for the time :/
Here my repo : 
https://github.com/Hydro8/constellation-packages/blob/master/Withings/Withings/Program.cs
I style have an error on Get "The name Get does not exist on the current context"

**Comment by antarr** [comment]
@Hydro8 How do I get the Constellation package. Its not showing up in Nuget

**Comment by Hydro8** [comment]
It's on beta and not available through nugget :/

**Comment by antarr** [comment]
@Hydro8  Are you able to share it with me? I can't build without it.

**Comment by antarr** [comment]
@Hydro8 Please try updating uninstalling Withings.NET and then searching for version 3.2.1
